build: off

install:
  - git submodule update --init
  - cinst jdk8 -version 8.0.172 -params 'installdir=C:\\jdk8'
  - SET JAVA_HOME=C:\jdk8
  - SET PATH=C:\jdk8\bin;%PATH%
  - curl -fsS -L -o jre.zip https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.161-1/java-1.8.0-openjdk-1.8.0.161-1.b14.ojdkbuild.windows.x86_64.zip
  - 7z e jre.zip -aoa
  - move java-1.8.0-openjdk-1.8.0.161-1.b14.ojdkbuild.windows.x86_64\jre pretixdesk\

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\jdk8 -> appveyor.yml
  - '%USERPROFILE%\.gradle -> appveyor.yml'

test_script:
  - cd pretixdesk
  - gradlew --no-daemon -version
  - gradlew --no-daemon --stacktrace clean check test build fatJar createExe
  - mkdir dist
  - '"C:\Program Files (x86)\NSIS\makensis.exe" windows.nsi'

artifacts:
  - path: pretixdesk\dist\pretixdesk.exe
    name: Installer

